services:
  backend:
    build: .
    container_name: hexflow-backend
    command: node server.js
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build: .
    container_name: hexflow-frontend
    command: npm run start:frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
